from typing import Protocol

from tui_app.domain.entities.entity import Entity


class EntityRepository(Protocol):
    """Repository port for Entity persistence."""

    async def save(self, entity: Entity) -> None: ...
    async def find_by_id(self, entity_id: str) -> Entity | None: ...
    async def find_all(self) -> list[Entity]: ...
    async def delete(self, entity_id: str) -> None: ...
